export const I18N = {
    "pt-br": {
        nav_about: "Sobre",
        nav_skills: "Habilidades",
        nav_projects: "Projetos",
        nav_contact: "Contato",
        hero_eyebrow: "Desenvolvedor Full-Stack",
        hero_title: "Marcos Kaiser",
        hero_subtitle: "Construo aplicações web modernas, responsivas e focadas em experiência do usuário.",
        hero_description: "Transformo ideias em produtos digitais completos, conectando interfaces bem cuidadas, lógica de negócio confiável e integrações eficientes.",
        cta_projects: "Ver projetos",
        cta_contact: "Fale comigo",
        about_kicker: "Sobre",
        about_title: "Perfil orientado a solução",
        about_p1: "Sou um desenvolvedor full-stack com interesse em criar experiências digitais claras, performáticas e fáceis de manter.",
        about_p2: "Gosto de unir design, código e produto para entregar páginas, sistemas e integrações que resolvem problemas reais.",
        skills_kicker: "Habilidades",
        skills_title: "Tecnologias e práticas",
        skill_front_title: "Front-end",
        skill_front_text: "HTML, CSS, JavaScript, interfaces responsivas, acessibilidade e animações leves.",
        skill_back_title: "Back-end",
        skill_back_text: "APIs, regras de negócio, autenticação, integrações e organização de dados.",
        skill_product_title: "Produto",
        skill_product_text: "Comunicação clara, foco no usuário, melhoria contínua e atenção aos detalhes.",
        projects_kicker: "Projetos",
        projects_title: "Seleção de trabalhos",
        project_status: "Em desenvolvimento",
        project_one_title: "Portfólio pessoal",
        project_one_text: "Landing page responsiva com tema claro/escuro, troca de idioma e animação SVG.",
        project_status_next: "Próximo destaque",
        project_next_title: "Seu próximo projeto",
        project_next_text: "Espaço reservado para apresentar um case real com contexto, desafios e resultados.",
        contact_kicker: "Contato",
        contact_title: "Vamos conversar?",
        contact_text: "Se você tem uma oportunidade, ideia ou projeto, posso ajudar a transformar o briefing em uma solução funcional.",
        contact_email: "Enviar e-mail",
    },
    "en-us": {
        nav_about: "About",
        nav_skills: "Skills",
        nav_projects: "Projects",
        nav_contact: "Contact",
        hero_eyebrow: "Full-Stack Developer",
        hero_title: "Marcos Kaiser",
        hero_subtitle: "I build modern, responsive web applications focused on user experience.",
        hero_description: "I turn ideas into complete digital products by connecting polished interfaces, reliable business logic, and efficient integrations.",
        cta_projects: "View projects",
        cta_contact: "Contact me",
        about_kicker: "About",
        about_title: "Solution-oriented profile",
        about_p1: "I am a full-stack developer interested in creating clear, performant, and maintainable digital experiences.",
        about_p2: "I like combining design, code, and product thinking to deliver pages, systems, and integrations that solve real problems.",
        skills_kicker: "Skills",
        skills_title: "Technologies and practices",
        skill_front_title: "Front-end",
        skill_front_text: "HTML, CSS, JavaScript, responsive interfaces, accessibility, and lightweight animations.",
        skill_back_title: "Back-end",
        skill_back_text: "APIs, business rules, authentication, integrations, and data organization.",
        skill_product_title: "Product",
        skill_product_text: "Clear communication, user focus, continuous improvement, and attention to detail.",
        projects_kicker: "Projects",
        projects_title: "Selected work",
        project_status: "In development",
        project_one_title: "Personal portfolio",
        project_one_text: "Responsive landing page with light/dark theme, language switcher, and SVG animation.",
        project_status_next: "Next highlight",
        project_next_title: "Your next project",
        project_next_text: "Reserved space to present a real case study with context, challenges, and outcomes.",
        contact_kicker: "Contact",
        contact_title: "Shall we talk?",
        contact_text: "If you have an opportunity, idea, or project, I can help turn the brief into a functional solution.",
        contact_email: "Send email",
    }
};
